### ISSUE TITLE
Missing level moves on some Legendary Pokémon introduced since Indigo Disk

### ISSUE THREAD

**Issue by giginet** [PokeAPI/pokeapi#1006]
@penelopeysm 

Thanks to #999, the newly learned moves were added. However, I found some data was wrong.

I notice all legendary Pokémon who introduced in this DLC have issues.
Strangely, their table lacks level moves and TM moves by the pre-existing TM.

This issue occurred in these Pokémon:

- 243 Raikou 
- 244 Entei
- 245 Suicune
- 249 Lugia
- 250 Ho-Oh
- 380 Latias
- 381 Latios
- 638 Cobalion
- 639 Terrakion
- 640 Virizion
- 643 Reshiram
- 644 Zekrom
- 646 Kyurem
- 791 Solgaleo
- 792 Lunala

They seem to be reflecting only moves learned by new TMs.

The legendary Pokémon introduced from HOME was not effected.

@penelopeysm, Could you take the time to fix this issue?
Thank you.

**Comment by penelopeysm** [comment]
Hello! I'm so sorry about this! It's probably because these are not in the actual Pokedex and I didn't have a complete list of all the Pokemon that could be transferred in.

Serebii does not have the new TM moves listed so I added those with a separate script, that's why those moves are in there.

I'll have a fix soon, and I'll also double check to see if there are any other cases that got missed out.
