### ISSUE TITLE
Types endpoint not returning values from Pokemon 19 onwards.

### ISSUE THREAD

**Issue by ItsTonyy** [PokeAPI/pokeapi#1090]
So I'm building a React and TypeScript app that simulates a Pokédex where I display various information about each Pokémon. One of these pieces of information is the weaknesses of each Pokémon. To retrieve this information, I made a request to this endpoint 'https://pokeapi.co/api/v2/type/{id or name}'. Everything worked fine initially, and the weaknesses were displayed. However, starting from Pokémon 19, all the JSON responses come back empty. And if I try to make requests using the Pokémon's name, I receive 'undefined'. Since I'm still a novice programmer, I apologize if all of this is a skill issue. 

Steps to Reproduce:

1. access "https://pokeapi.co/"
2. Make a request to "https://pokeapi.co/api/v2/type/18", the correct data will come
3. Make a request to "https://pokeapi.co/api/v2/type/19", the response is gonna be empty objects

![image](https://github.com/PokeAPI/pokeapi/assets/112224948/762558d9-f3c5-4094-89b8-a7a0db5a1cc2)

**Comment by GreatNovaDragon** [comment]
Type 19, the stellar type is a frankly very special type, where its damage relations are not in relation to what type the pokemon is, but if its in the state of terastalation or not. Therefore, the damage_relation field cannot be filled

Type 10001, the ???, which was an type that only existed because Curse had it, and something a pokemon can only have it, similarly has no damage relation. 

Type 10002, the Shadow Type, is also a very special type, In the pokemon colloseum games there is the category of Pokemon named Shadow Pokemon, which is not an additional type on the pokemon itself, but they learn Shadow Moves (ingame not even displayed as a type, but basically acting as one), that deal specific kinds of damage, Shadow Moves deal very effective damage if the opposing Pokemon is not a Shadow Pokemon

**Comment by GreatNovaDragon** [comment]
Basically, its intended that there is no data, cause there IS no data
