### ISSUE TITLE
Pokémon Sun & Pokémon Moon FAQ

### ISSUE THREAD

**Issue by phalt** [PokeAPI/pokeapi#112]
TL;DR we'll try and add the information as we get it, but we don't want to add information that is hearsay or speculative. We'll prefer to wait for trusted sources rather than add little bits of information as we go.

As more is found out about Sun & Moon, we'll be happy to discuss it here.

**Comment by zaneadix** [comment]
@phalt nice thinking :)

**Comment by nimaje** [comment]
@phalt  +1
but Veekun will have to add the same data, if they support `Pokémon Sun` and `Pokémon Moon`. Because of  DRY (Don't Repeate Yourself) I suggested a data repo (https://github.com/phalt/pokeapi/issues/102#issuecomment-185292046) which could be used together with Veekun and others who need the "raw data".
(Should I open a new issue to discuss this or do you don't want this in general?)

**Comment by phalt** [comment]
@nimaje yep you're right - and this is why I opened this issue. When I say trusted sources I basically mean Veekun's data :) Do we need an extra repository if Veekun has the data? Why not just make fork in this project?

**Comment by mikazo** [comment]
Hey, since Sun & Moon come out this week, I will happily lend a hand with any work that needs doing to get the new data added to the API. Just let me know!

**Comment by Pokemonleaks** [comment]
does anyone have a black screen after becoming the champion in pokemon moon???? i keep getting a unimplemented function 'StoreDataCache'. does anyone know how to fix this?

**Comment by acz13** [comment]
I suggest using the smogon data miner's info

it's pretty reliable

**Comment by pixelgruff** [comment]
I'm also available for helping get Sun & Moon information into the API.  I run a Discord bot against the PokeAPI and my friends and I would love the new data.

**Comment by Sidaroth** [comment]
I'm not sure how useful this will be for your gen7 updates, but here's the data i'm using:
https://github.com/Sidaroth/Pokedex/blob/master/gen7out.csv
Keep in mind this is mostly taken from pokemonDB.net, and if there are any errors there they will be reflected here as well. My data does not contain everything that pokeapi keeps track of either, but it may be helpful.

**Comment by DaveRGP** [comment]
There are a couple of other places, with full stats now: 
http://www.serebii.net/pokedex-sm/bug.shtml
http://pokemondb.net/pokedex/rowlet
http://pokemongohub.net/pokemon-sun-moon-alola-pokedex-stats-moves-types/

Not checked the veracity of the values, but they seem complete in each record.

**Comment by torjinx** [comment]
I'm eager to help with this in any way I can! My go-to resources:
http://poemondb.net
http://www.smogon.com/forums/threads/pokemon-sun-moon-battle-mechanics-research.3586701/

What's the game plan? How long should we wait to be sure data is reliable?

**Comment by LutariFan** [comment]
I would also like to help out if possible. I would say there has been enough research done by now for the data to be reliable.

**Comment by LeonMB** [comment]
Would be awesome to have sun and moon data, are there any plans to update the data set for gen 7?

**Comment by acz13** [comment]
Every plan is in this thread probably

**Comment by metaunicorn** [comment]
FYI @phalt I´ve created a CMS capable of importing and exporting Veekun CSV data, with some improvements to the CSV files: https://github.com/metaunicorn/pokedex-admin

I created it in order to make it easier to everyone to understand the data structure and being able to complete and fix it easier. I tried to tell @ eevee but I got no response from her/him.

So anyone willing to contribute will be welcome. I am currently filling the Sun and Moon data with that CMS tool, but lots of informations are missing (pokemon color, habitat, and other misc. data).

If anyone has access to this raw data dump from the original games, please contact me.

**Comment by metaunicorn** [comment]
I think we can reuse lot of info from the Showdown project aswell, but I don't know what may be missing yet,... lots of things to fill in these CSVs :_) 

https://github.com/Zarel/Pokemon-Showdown/blob/master/data/pokedex.js

I hope I can simplify all of these CSVs in the future, first my prio is to bring Sun Moon data to this known veekun format.

**Comment by acz13** [comment]
http://phalt.co/pokeapi-and-swapi-going-forward/
