### ISSUE TITLE
Modified / created datetime stamps

### ISSUE THREAD

**Issue by sargunster** [PokeAPI/pokeapi#140]
The documentation of both v1 and v2 state that "we provide modified/created datetime stamps on every single resource so you can check for updates (and thus make your caching efficient)". However, I only see these datetime stamps on v1 responses, not on v2 responses. This is either a bug in the API or in the documentation.

If it's a bug in the documentation and datetime stamps were removed intentionally for v2, what's a good amount of time to cache results? One week? Is there a good way to check for updates?

**Comment by phalt** [comment]
@sargunster it's likely that we've just missed those attributes in the representation responses. I think we definitely have those values in the database, am I right @zaneadix ?

**Comment by zaneadix** [comment]
@phalt Totally dropped the ball on this one. The inclusion of it in docs was honestly in error.
Originally when I was working on the models I got stuck trying to think of how to handle created/modified because the models were made up of many different things. For example; Pokemon descriptions are not their own callable resources anymore so a created/modified date didn't really make sense. Really we would want to set a modified date on a Pokemon resource if it gained a new description or if one of the descriptions had changed (right? really not 100% sure). Over the course of the year working on things I clearly just forgot about these fields entirely.

**Comment by phalt** [comment]
@zaneadix hehe don't worry man there were many things going on, easy to miss something like this. I say we either remove from the docs for now or mention it as a planned feature. Adding it in to the base models should not be difficult.

**Comment by Kronopt** [comment]
The V2 documentation still mentions the existence of the modified/created datetime stamps, but no resource that I sampled has it implemented.

Is it going to be implemented at all?
If not, I think the information in the documentation regarding the modified/created attributes should be removed

**Comment by Naramsim** [comment]
Yep, it should be removed, can you open a PR for this?
