### ISSUE TITLE
Most `evolution-chains` are missing 

### ISSUE THREAD

**Issue by retep-mathwizard** [PokeAPI/pokeapi#159]
on higher numbers (id 374 +), most `evolution-chains` say `{"detail":"not found"}`. Have these not been implemented yet? Example: http://pokeapi.co/api/v2/evolution-chain/567 If so, how soon will they be added? Also, some id's are not working, http://pokeapi.co/api/v2/pokemon/129/.

**Comment by mjhayes412** [comment]
Ah, you must be expecting evolution-chain/567 to be archeops.  What I think is going on is the id references the chain's primary key in the table and has nothing to do with the pokemon's id.  That's why evolution-chain/1 give bulbasaur and evolution-chain/2 give charmander.

But I think you're on to something.  This should be a change request to have the evolution-chains request be based on pokemon id.

And pokemon/129 does exist, it's just ridiculously huge.  It's magikarp.  Can you imagine how many records exist for its encounter location?  Doesn't every version have an old-rod lol

Now that's one I'd like to optimize.  Good catch!  Keep'em coming.

**Comment by phalt** [comment]
@retep-mathwizard @mjhayes412 Hey, thanks for looking into this. Some Pokémon (Zubat is the best example of this) have so many encounter locations it fails to load. We're hoping to optimise this soon.

And you're right @mjhayes412 - Primary Keys are not Pokémon National Pokédex numbers.

**Comment by retep-mathwizard** [comment]
I just realized that about each one being grouped by 3's or 2's! Thanks. Is
there a way to find the link to the evolution-chain from the pokemon? I
couldn't find the link directly, at http://pokeapi.co/api/v2/pokemon/1/,is
there a way to get to it?

**Comment by zaneadix** [comment]
@retep-mathiwizard    Check out the pokemon-species resource. These have evolution chain references. You should really point to Pokemon resources from Pokemon-species resources.
