### ISSUE TITLE
Mechanism to find any changes made to the API data

### ISSUE THREAD

**Issue by vaikan** [PokeAPI/pokeapi#205]
Since timestamp is not used in the current V2 API, I would like to ask if there is any other method to detect changes to the API data. I have been storing the data in the browser using LocalStorage and would love to update the data when any changes occurs in the API.

**Comment by phalt** [comment]
@vaikan I believe timestamps are just missing and need to be added.

**Comment by sargunster** [comment]
See the discussion in #140

**Comment by snotyak** [comment]
@phalt Is this something that's going to be added? I'm caching my results, but I check for updates every few days by redownloading and checking for differences (and performing waaaay more API calls than I need to be).

**Comment by sargunster** [comment]
The problem is that each resource is generated from a bunch of different things. Maybe just a global timestamp reporting when the database was last changed is sufficient?

**Comment by snotyak** [comment]
@sargunster That would be much better than nothing.

**Comment by vaikan** [comment]
@sargunster adding a global timestamp should do the trick.

**Comment by sargunster** [comment]
@phalt @zaneadix Thoughts on a global timestamp? Should be easy to implement, just set it when the DB build script runs. IMO it's not perfect but can get the job done for the common use cases.

**Comment by phalt** [comment]
I believe this fix would do what we want: https://github.com/PokeAPI/pokeapi/issues/140 

The updated_time would be the time the db is updated.

**Comment by zberk** [comment]
Maybe this is beyond the scope of this particular issue, but it would be very useful to know which resources should be updated between timestamps. For example, I wouldn't want to reload all the pokemon-species if only contest-effects changed.

**Comment by phalt** [comment]
@zberk can you explain more what you're looking for?

Every resource would have an individual timestamp.

**Comment by snotyak** [comment]
@phalt I think he's saying to have that global timestamp, but in addition to that have a list of resource types that have been changed with that "update". It sounds like a great idea at first, but makes less sense because once that timestamp is changed, the previously changed resources will be overridden by the new ones, so if you're more than 1 update behind, you won't get everything. The way to make that work would be to maybe have a changelog object in the db that has a date modified, a list of resources that have been changed, and some insignificant version number. I think that sounds like a better solution than the global timestamp and is likely a lot easier to implement than adding timestamps to every resource.

**Comment by phalt** [comment]
Given the data set rarely sees significant changes, I think this is a bit over kill for the effort of creating it in order to provide this functionality. We make 3-4 bug fixes to data a year, as well.

**Comment by sargunster** [comment]
For me, the primary use case for timestamps is to check if I need to redownload the data. If the timestamp is attached to the object, then I have to make a request for each object anyway to check timestamps. 

I think a single global timestamp would work. Alternatively, there could be a single timestamp per endpoint, but I'm not quite sure how to implement that since each endpoint pulls data from multiple tables.

They way I see this working:
 - When either the code or the database changes, the timestamp is saved somehow
 - The user can request this timestamp via something like `/api/v2/updated` and redownload all data when this is updated

This lacks details on which resources were updated, but I think it's sufficient since updates are infrequent anyway.

**Comment by phalt** [comment]
Yup, but you shouldn't be redownloading all the data at once - what percentage of that data is actually used by a given user? If I cache the entire API once but only 1% is used, then it's inefficient to store it.

If we timestamp individual resources and compare the timestamp when I look it up again and it's older than X many days, I can make a request to check and see if it's new, if it is, store the new data.

**Comment by snotyak** [comment]
In that case, I think a single global timestamp would suffice, though don't you think there will be **many** frequent changes once S/M come out?

**Comment by snotyak** [comment]
Since the date set rarely sees changes, I think a single global timestamp would suffice. However, don't you think there will be many frequent changes once S/M come out?

If you did go the per-resource route, it would be nice to have a separate endpoint `/api/v2/updated?limit=x&lastUpdated=someDateTime` that works just like any other resource list and would return a list of resources that have been modified/created after the provided time.

**Comment by sdcinglis** [comment]
Could we not just include lastUpdated in the resource lists? `/api/v2/pokemon/` would return:

`{
	"count": 811,
	"previous": null,
	"results": [
		{
			"url": "http://pokeapi.co/api/v2/pokemon/1/",
			"name": "bulbasaur",
			"updated": 1467060675
		},
		{
			"url": "http://pokeapi.co/api/v2/pokemon/2/",
			"name": "ivysaur",
			"updated": 1467060675
		},
		{
			"url": "http://pokeapi.co/api/v2/pokemon/3/",
			"name": "venusaur",
			"updated": 1467060675
		}
...`

**Comment by sargunster** [comment]
What's the best way to implement this in the code? Does Django provide something to get the last updated time of a table? Or will we have to maintain the updated time ourselves?

**Comment by sdcinglis** [comment]
I don't know about django but if the database is sql based there's usually the ability to add a column that is the current timestamp on insert/update.

**Comment by sargunster** [comment]
Ah, you're right, I forgot about that. The database uses PostgreSQL. Just
have to edit the build script to add that column in each table.

**Comment by sdcinglis** [comment]
How is new data usually applied to the DB? Do you loop through all of the data from the veekun csvs and do an INSERT INTO ... ON DUPLICATE KEY UPDATE query? If so that may need to be reworked to only update the rows when something has definitely changed otherwise the update field may be changed erroneously.

**Comment by nimaje** [comment]
Should be the build script (https://github.com/PokeAPI/pokeapi/blob/master/data/v2/build.py) basically delete and then recreate. (You have to ask @phalt how he handles it, to know for sure, but other methodes seem impractical with the scripts and data)
This would be a problem with changed timestamps for every resource.

**Comment by sargunster** [comment]
I think the build script changes should go on top of the code in #169? Since that's such a large change to the build script, we don't want to have two conflicting large changes to the same script. @phalt are there plans to merge that PR?

**Comment by sdcinglis** [comment]
If the standard is to drop tables and rebuild every update then the lastUpdated timestamp for individual items isn't very valuable, unless veekun also maintains that data somewhere. Unless we want to totally rewrite the build script to update and check for differences before inserting I think a single universal timestamp is a good stop-gap solution. Good play around with a mysql server and see if there's a nice way to handle this.

**Comment by sdcinglis** [comment]
Alright, so I did some exporation and I found a query format that might help.

`INSERT INTO test
(id, data, timestamp)
VALUES(0, "Testing", now())
ON DUPLICATE KEY
UPDATE timestamp = IF(data=VALUES(data),timestamp,VALUES(timestamp)),
data = VALUES(data)`

This will insert the values 0, "Testing", and the current timestamp into a table, if something already exists with the the same id (the primary key) then it will set the "data" column to the new value, and the timestamp value to the current timestamp IF the data is different than it was before. It's kind of gross and with more fields it would be even grosser but it would solve this issue.

**Comment by looperhacks** [comment]
Another way to reduce load for unchanged resources could be achieved by honoring the If-Modified-Since HTTP header and returning a [304 *not modified*](https://httpstatuses.com/304) status code (if the resource hasn't been modified).

**Comment by phalt** [comment]
It feels like this has gone off on a tangent that is ignoring the fact that we can add modified/created attributes easily. Django models support date time fields that are set when created, and also when they're last updated. All we have to do is add them into the responses that are sent out.

Look at SWAPI, another API that I built, and it does exactly what we need to do: https://github.com/phalt/swapi/blob/master/resources/models.py#L6L14

**Comment by sdcinglis** [comment]
Ah well that's a lot easier. I was thinking in purely SQL terms.

**Comment by phalt** [comment]
@sdcinglis Django's ORM will handle talking to the database and dealing with date time fields for us :)
