### ISSUE TITLE
Indication of which resources can be called by name

### ISSUE THREAD

**Issue by sargunster** [PokeAPI/pokeapi#216]
It would be useful to have some indication of whether a resource can be requested by name and id or just by id.

Possible implementation:
Two new boolean fields on the resource list object: `request-by-id` and `request-by-name`.

Use case:
The PokeKotlin tests will be able to check whether I have implemented a client method for all resources that accept names. In the future, I also plan to use a code generator which will generate the client methods based on the information at https://pokeapi.co/api/v2 and the new `request-by-id` and `request-by-name` fields.

Current workaround:
I can request a resource by name and check if there's an error.

**Comment by phalt** [comment]
It's a good idea, I think it points at a wider question though:

Do we really need different ways to uniquely identify a single resource? Beyond the human-usability aspect where `api/v2/pokemon/bulbasaur` is better than `api/v2/pokemon/1/`, what benefit is there? Especially when, as the issue you've raised, there is confusion about where this works?

The original reason I added it to V1 was so that a single resource, Pokemon, could be looked up by name, to help with new programmers finding their favourite Pokemon quickly. It wasn't a technological reason, and it was quite Hacky. `Abra` and `Kadabra` would both return the same resource due to the way I inspected strings.

For clients that are integrating with the API and (hopefully) adopting good API discovery and traversing practices, do they need to be able to use multiple ways to look things up?

**Comment by sargunster** [comment]
That's a great point. I only use request by name when polling the API manually to check some things, not from my code. I only really planned to add the feature to the PokeKotlin client because the feature was there in the API. I think it's reasonable to deprecate request-by-name, and then I can feel comfortable not including the feature in the PokeKotlin client.
