### ISSUE TITLE
[Question] How to handle rate limiting ?

### ISSUE THREAD

**Issue by Sharlaan** [PokeAPI/pokeapi#282]
Thanks for this nice pokemon API

For my project (React/Redux, client only webapp), i need to calculate and display average stats.

Which technique would you advice me to fetch all pokemons without meeting the frightening error 429 "Too many requests" ?

So far i tried (using JS native Fetch API, client-side) :
1. GET all IDs from `https://pokeapi.co/api/v2/pokemon/`
2. then pokemons = listIDs.map(async id => await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`))
3. From there i would be able to implement my caching and calculations, but ...

Problem the server seems to not like that at all and make the relatively tiny 5mb data download more than 30 mins when not spitting a 429 response for half requests ....

A concrete example of what to do / not to do on main docs page would be nice.

EDIT: also took me quite some time to find th endpoint for descriptions, here it is for whoever searching it:  `http://pokeapi.co/api/v2/pokemon-species/${id}/` then check the property `this.flavor_text_entries`
unless there is a better way ?

**Comment by bretgourdie** [comment]
Since you're having problems with getting everything in one go, I would recommend simplifying the initial data set. Do you need EVERYTHING from the get-go? Since you get the Pokemon names from the all IDs call, you can display that to select from. When one is selected, grab the stats and calculate. Consider having a "shopping cart" comparison tool to compare things side-by-side. Alternatively, create lists of important Pokemon (fully evolved, Little Cup qualifiers, etc.) and make a category selection to pull a smaller set.

If you need EVERY Pokemon, consider a one-time load that your client stores to use with subsequent runs. That way, the client only needs a one-hour startup once; after that, it's good to go for a few years until the next game comes out. With this approach, you'll just continue hitting the server until your 429 becomes a 200, however long that takes. Next time, your client will load data from its database you create with the API data. If you store the database server-side, every client will benefit from it! Caching is in the terms of use, after all.

**Comment by Sharlaan** [comment]
Here is what happened with team lead :

TL: "Nice work, we can see the pokemons list, can check each pokemon's details by clicking on one from list, ...."
me: "thanks !"
TL: "... where can i compare for example this pokemon's stats, with others, no average comapirosn anywhere ? Our customer asked for this feature."
me: "well... check this progress bar on top of page it's currently at 1% from fetching other pokemons stats and only then the details chart will be able to show the ...."
TL: "You're fired !"

Just exagerating a bit the picture but see.... i've indeed implemented a cliant-side database PouchDB, filled progressively from a fetching layer brute-forcing the API server. I consider myself lucky my IP didnot get banned yet XD.

I guess my best option is to convince our customer he needs a server to store those mean values once, so can distribute them to clients without brute-forcing the API server,

Other thing i'm wondering: the responses i'm getting from `https://pokeapi.co/api/v2/pokemon/${id}` endpoint don't have some ETA header so i could check out for outdated data ?

**Comment by bretgourdie** [comment]
The whole idea behind a REST service is that your IP won't get banned; the server will just reject your frequent requests (as you've experienced).

As to the created/modified dates, this is a documented issue at #140, discussing a global updated timestamp at #205.
