### ISSUE TITLE
Pokemon Sound?

### ISSUE THREAD

**Issue by laurenceHR** [PokeAPI/pokeapi#292]
I'm developing a Pokedex Alexa Skill (you can found as Unofficial Pokedex), that can be so awesome if I include the sound of each Pokemon, like a 'pika pika' hehehe.
Exists in any place all pokemon sound audio files?

**Comment by tdmalone** [comment]
Try http://git.veekun.com/pokedex-media.git/tree/HEAD:/pokemon/cries

But you should probably ask this on Slack (see the Slack heading at http://pokeapi.co/docsv2/) - it's not an issue with PokeAPI :)

**Comment by tdmalone** [comment]
See also https://github.com/PokeAPI/pokeapi/issues/242

**Comment by NobleUplift** [comment]
Glad to see someone else thought of this before I did @laurenceHR! I got back into my Blue Version last year and beat it for the first time since childhood, working on my Red Version right now, and I hate using Bulbapedia to look up information on mobile. Takes way too long to load.

How's development of your Alexa Skill going?
