### ISSUE TITLE
Types' color

### ISSUE THREAD

**Issue by feddycap** [PokeAPI/pokeapi#326]
You could put the color of the type in the type data, it would be very helpful for the situation in which someone wants to have a panel representing the type.

**Comment by Naramsim** [comment]
Ciao @feddycap, I think the best thing you can do is to have on your own a map with all the colors.

Here if you want the 'official' badges, and you can extract the color from there using Developers tool (https://veekun.com/dex/media/types/en/)

We most likely won't add color to our API, since all the raw data comes from Veekun.
