### ISSUE TITLE
Pokemon heights inaccurate

### ISSUE THREAD

**Issue by nnguy152** [PokeAPI/pokeapi#334]
Hello, 
I’m trying to make an app that gathers the height of pokemon based on user input and the decimeters vary about 3 inches from actual pokemon height (listed on bulbapedia)

Will there be any update where height is converted to a more accurate measurement? I know that’s not really important, I just wanted to see. Lol

**Comment by ahester57** [comment]
Pokémon of the same species may vary in height.

**Comment by tdmalone** [comment]
All of the data on PokeAPI comes from [Veekun](https://veekun.com/). Are the heights off there as well? If so you might need to log an issue there :)

**Comment by nnguy152** [comment]
ahester57- Probably but having it stick to a solid average height per pokemon would be nice. 

Tdmalone- That’s so cool. Veekun actually has measurements in both feet/inches and meters. The feet/inches is super accurate but meters has it rounded. Like for example, on Veekun, Blastoise is 5’3 and 1.6m but heights from 5’2 - 5’6 round to 1.6m. :,)

**Comment by cmmartti** [comment]
Veekun stores heights in decimetres, not inches. All of our data comes from Veekun, so if there's an issue with incorrect data, submit an issue on their GitHub repo.

In any case, Bulbapedia, Veekun, and PokéAPI all show the same value of 1.6 m for the example given (Blastoise), so I don't see what the issue is.
