### ISSUE TITLE
Is there an endpoint that returns a pokemon's image as in the game's pokedex?

### ISSUE THREAD

**Issue by nats12** [PokeAPI/pokeapi#346]
Can't seem to find anything  about pokemon icon/image in the documentation or in the object returned listing each pokemon. Are there any for icons and if not, will there be soon?

**Comment by Naramsim** [comment]
https://github.com/PokeAPI/sprites

https://pokeapi.co/api/v2/pokemon/23/ -> look in sprites

**Comment by sashafirsov** [comment]
https://unpkg.com/pokeapi-sprites@2.0.2/sprites/pokemon/other/dream-world/87.svg

**Comment by Naramsim** [comment]
@sashafirsov, cool implementation. Would you be willing to port it at our official repo?

**Comment by sashafirsov** [comment]
@Naramsim, there are technical challenges in publishing the pokeApi sprites original repo you most likely aware of. 
`npm publish` is generating  the descriptor string more then 0.5Gb which crashes this node process. At the moment there is no ability to change this limit as it is hardcoded in V8 JS engine. 

I have to remove all PNG( ~5Gb) files in fork https://github.com/sashafirsov/pokeapi-sprites
in order to make project publish-able in nodejs.com  

Looking into popularity of https://github.com/PokeAPI/sprites such removal from original project does not look possible unless the PNG generation could be moved into separate repo or build step. 

While publishing to npmjs.com is still possible by making PNG excluded from package, I am not sure about happiness of npm users from github url `npm install github:PokeAPI/sprites`. 

From another side, I do not see the PNGs as valuable resource as most sizes and color variations could be rendered 1:1 by SVGs. The color variations also could be tuned on CSS or rendering level. IMO v3.0 could take this pattern as base and as such would not have restrictions in npm and CDN publishing. If there is an interest in such bold move, we could continue.

**Comment by Naramsim** [comment]
Ahh, I see your point. I didn't know about the limit. Well thanks again :)

**Comment by sashafirsov** [comment]
Does this one has a sense to be shared in PokeAPI community? 
[PokéAPI Explorer](https://unpkg.com/css-chain-test@1.0.7/src/PokeApi-Explorer.html)

**Comment by Naramsim** [comment]
It's broken on my side

**Comment by sashafirsov** [comment]
CDN link is broken, will fix in a bit.

**Comment by sashafirsov** [comment]
https://unpkg.com/css-chain-test@1.0.8/src/PokeApi-Explorer.html seems working, looking where in PokeAPI it could be embedded. Perhaps in https://pokeapi.co/

**Comment by Naramsim** [comment]
I don't know @sashafirsov, I find it a bit difficult to use. What's the exact point you are trying to fix with this tool?

**Comment by sashafirsov** [comment]
@Naramsim, the initial intent was to show images from https://github.com/PokeAPI/sprites in relation to API.  

I had trouble to understand the relation between those images and API and urls in data. With this "API explorer" minimal visualization of data and cross-linking API URLs, it become more clear. While it is not a developer tool for working with API, it is a **teaser for API and image** consumers. 

Perhaps embedding or link to REST playground or [GraphQL API console](https://beta.pokeapi.co/graphql/console/) could be useful for such audience. Personally I would find such "visual preview" useful as a tab in data preview section of "Try it now" on [pokeapi.co](https://pokeapi.co)

Unlike [Pokemon Wiki](https://pokemon.fandom.com/wiki/Pok%C3%A9mon_Wiki) it is not oriented to give full info about pokemon games, just show what API has. 

It immediately exposed that 1118 pokemon count does not match all 649 images in dreamworld. Which mean I have chosen either a wrong API to list all pokemons( https://pokeapi.co/api/v2/pokemon ) or image library is missing half of assets( https://unpkg.com/browse/pokeapi-sprites/sprites/pokemon/other/dream-world/ ). That was starting point to make a decision whether to use images from https://github.com/PokeAPI/sprites. With 650 "official" it would be OK, unofficial have to be filtered off  or SVG images replaced with PNG. "visual preview" could help with finding what data could be used for recognition of non-official and what image to use as substitution.

PS. could you describe "difficult to use", please? I assume you had some kind of expectations and it did not match. What it is?

**Comment by Naramsim** [comment]
Hi @sashafirsov, I see what you mean. If we go for such a solution/tool ideally it would be better if it could query every endpoint and that every property is returned. Right now your tool is only returning properties that have a list as a value. I would also use a standard tool, I don't know if API explorers are a thing. 

The ultimate goal of the tool would be to showcase what is present in each endpoint visually and live. On one side we already have the documentation that allows people to see what's exposed by each endpoint, but the docs aren't live and you cannot _try_ them as you would in Swagger. 

By difficult to use I meant, difficult to understand. The mechanism that allows you to see and query inner resources tends to produce a lot of output and in the end, the webpage becomes a mess. 

If your main intent was to list each and every sprite dynamically for a Pokemon, I think it would be better to stick with that goal. Otherwise maybe looking online for some API explorer tool would be much simpler than coding everything _in-house_.

**Comment by Naramsim** [comment]
For the sprites you are right, we don't have a place where one can see if every `pokemon` has a particular sprite. We could extend our docs with the counts of each sprite folder, so that developers know that some sprites are missing

**Comment by rasolofonirina** [comment]
You also can use https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemonIndex}.png as indicated on : https://stackoverflow.com/questions/69239521/unable-to-display-pokemon-image-from-pokeapi-co

**Comment by jayk-gupta** [comment]
> Can't seem to find anything about pokemon icon/image in the documentation or in the object returned listing each pokemon. Are there any for icons and if not, will there be soon?

 I too can't find it working in my api. Is there any other alternative for using pokemon images?!

**Comment by C-Garza** [comment]
@jayk-gupta Are you looking for the pokemon icons like in a pokedex? Because they do exist: [https://github.com/PokeAPI/sprites#icons](https://github.com/PokeAPI/sprites#icons)

Ex: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/icons/25.png

**Comment by justingolden21** [comment]
The vector art is awesome, but ends at 649 (https://unpkg.com/pokeapi-sprites@2.0.2/sprites/pokemon/other/dream-world/649.svg). Was wondering if there is any repo with vector art of all current pokemon (tall order, I know, and yeah I know it would probably have to come from some game)
