### ISSUE TITLE
Why are Pokemon height and weight ten times their actual value?

### ISSUE THREAD

**Issue by arnavb** [PokeAPI/pokeapi#380]
When I create a sample request for a pokemon, say Garchomp (445), I get that its weight is stored as 950 (950 what?) and its height `19`. Checking bulbapedia and pokemondb, I see that these values should be 95.0 and 1.9 respectively. Evidently, these values are ten times what they should be. This can be seen with other pokemon as well. Since JSON supports floating point numbers, why not just place the actual value for these fields?

**Comment by Naramsim** [comment]
We take our data from Veekun.

We do not modify their data.

**Comment by tdmalone** [comment]
Just to clarify this... @arnavb it's a good question, and you're welcome to open an issue at Veekun about it: https://github.com/veekun/pokedex/issues

If there's a good reason Veekun can't/won't change the data and that same reason doesn't apply to PokeAPI, I suppose we _could_ make a case for adjusting the data, but it would probably not be ideal as it would introduce additional complexity to the management of the API.

Having said that, there's probably a case for adding a little more details on these fields in our documentation. I'll open an issue in the pokeapi.co repo for that.

Thanks for reporting!

**Comment by Anu6is** [comment]
Just a note on this. While it may not be a breaking change as such to "correct" these values, it can have an impact on projects that are consuming these values as is and making the necessary adjustments internally.

**Comment by tdmalone** [comment]
^ That's a good point. If we changed them, it would have to be an API version increase for that reason.

**Comment by sargunv** [comment]
I'm not sure why we need to discuss making a breaking change for this. Just
update the docs to mention we report height in decimeters. Our number isn't
incorrect, we just need to clarify units.

**Comment by tdmalone** [comment]
@sargunv That's why this issue is closed and https://github.com/PokeAPI/pokeapi.co/issues/19 is open instead :)

**Comment by sargunv** [comment]
Cool, just following from email so I didn't notice it's closed :)

**Comment by phalt** [comment]
Doesn't need a change. It's the data we consumed originally.

In software you can just divide by 10 ;)

**Comment by tdmalone** [comment]
Thanks for checking up on it!

While I agree it would make more sense for us to be presenting the values divided by 10, given the feedback in this issue I'm not sure we should now, because:
- there's no precedent for us adjusting the Veekun data, so introducing an adjustment introduces extra complexity into the management of the API
- it'll be a breaking change, so can't be done without incrementing the API version
- the change on its own doesn't offer a lot of value so isn't really worth the effort, given it's trivial to divide by 10 in downstream apps (especially now that we've just [merged a PR](https://github.com/PokeAPI/pokeapi.co/pull/20) adding the units to the docs)

This is probably worth revisiting in a future API release - _if_ and when that comes - but it's not something we can support at the moment I'm afraid!

**Comment by arnavb** [comment]
Cool, thanks for the clarification!
