### ISSUE TITLE
No Pokédexes for Sun and Moon

### ISSUE THREAD

**Issue by schwigri** [PokeAPI/pokeapi#391]
If you visit the version group for Sun and Moon (https://pokeapi.co/api/v2/version-group/17/) there are no Pokédexes; if you visit the Pokédexes page (https://pokeapi.co/api/v2/pokedex/) it only has them up to Omega Ruby and Alpha Sapphire.

**Comment by cmmartti** [comment]
We get our data from [veekun](https://github.com/veekun/pokedex), and they don't have the data either. It looks like there is an open issue there for this at veekun/pokedex#217.

It's a bit of a dilemma, because the data can only be updated by manually pulling it from the game ROMs, and only a few people know how to do that. I have no idea what the process entails, nor am I prepared to jump into that.
