### ISSUE TITLE
Power-Up Punch Reporting as HM06 in ORAS

### ISSUE THREAD

**Issue by lucasdeholanda** [PokeAPI/pokeapi#392]
https://pokeapi.co/api/v2/move/612/
https://pokeapi.co/api/v2/machine/1209/

**Comment by Naramsim** [comment]
Hello, could you please verify if the error happens also here? https://github.com/veekun/pokedex

This is our source for our API.

**Comment by lucasdeholanda** [comment]
https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/machines.csv
As far as I can see it's correct. Both entries for the move 612 are associated with TM98.

By coincidence, I just found out that Wild Charge (TM93) is associated with HM01 as well.
The last update on the file shows "Fix TMs 93-100 refer to the wrong item in OR/AS", so that's probably it.

**Comment by Naramsim** [comment]
Hi, we also got that piece of data: https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/machines.csv#L1307

It means that we are currently serving old content, we should reload our data on our servers. ATM we are currently in a strange situation since we serve static files scraped from our own API. @sargunv, would you give another try to scrape new data from the API using the latest version of pokeapi? @cmmartti, did a lot of improvements and now we run on Python 3, with our dependencies updated. Maybe Pokeapi will not crash anymore.

**Comment by cmmartti** [comment]
PokéAPI has been updated with new data from Veekun. @lucasdeholanda Can you confirm that the error has been fixed?
