### ISSUE TITLE
API results only showing the first 19 items of a list

### ISSUE THREAD

**Issue by wcshamblin** [PokeAPI/pokeapi#407]
When I visit https://pokeapi.co/api/v2/pokemon/, it only shows the first 19 pokemon of the pokedex. 
The same applies for berries: https://pokeapi.co/api/v2/berry, moves: https://pokeapi.co/api/v2/move, and items: https://pokeapi.co/api/v2/item.

I don't really understand why this is happening, but this morning it was showing all items, pokemon, and berries on the same page. It must've changed a couple hours ago. Is this intentional or is it a bug? 

Thanks!

**Comment by cmmartti** [comment]
Very much intentional. The behaviour before was incorrect, and was a side-effect of stop-gap measures that were put in place this fall after an outage, and was only fixed today when we finally finished the move to new static hosting.

The default page size is 20, [as explained in the documentation](https://pokeapi.co/docs/v2.html#resource-lists). If you want a larger page, add a larger `limit` query parameter, or use `offset` to request the next page. For example, https://pokeapi.co/api/v2/pokemon/?limit=100&offset=200 will request the third page of 100 resources.

**Comment by cmmartti** [comment]
Although I've noticed that the `offset` parameter is non-functional, even though `limit` works... that will have to be fixed.

**Comment by wcshamblin** [comment]
Thanks! Maybe it's bad practice to use it in that way but it speeds up my code a ton.

**Comment by wcshamblin** [comment]
Oh, is there any way to set a max limit? I can't find anything on that in the docs. Setting limit to 9999 feels wrong.

**Comment by cmmartti** [comment]
Stick to a nice round 1000, which is more likely to be cached.

**Comment by wcshamblin** [comment]
Good enough, thanks
