### ISSUE TITLE
Missing Aegislash

### ISSUE THREAD

**Issue by 2sodiumsandwich** [PokeAPI/pokeapi#425]
Aegislash is not in the pokemon database

**Comment by Kronopt** [comment]
He actually is.
But because he has different forms, you can't find him by searching for his name.

If you query the API like this:
https://pokeapi.co/api/v2/pokemon/aegislash
an error will be returned.

But if you query by id, like this:
https://pokeapi.co/api/v2/pokemon/681
it will work.

To get a specific form by name, you can do it like so:
https://pokeapi.co/api/v2/pokemon/aegislash-shield
https://pokeapi.co/api/v2/pokemon/aegislash-blade

**Comment by 2sodiumsandwich** [comment]
Ok thank you

- Kevin

________________________________

**Comment by Kronopt** [comment]
This can be closed.

**Comment by jev217** [comment]
This Pokemon still shows up as "not found"
https://pokeapi.co/api/v2/pokemon/aegislash

**Comment by Naramsim** [comment]
> This Pokemon still shows up as "not found"
> https://pokeapi.co/api/v2/pokemon/aegislash

Query the pokemon-species endpoint
