### ISSUE TITLE
Search for a pokemon in another language

### ISSUE THREAD

**Issue by MalronWall** [PokeAPI/pokeapi#470]
Hello there ! :)

For my application, I would need to do a search on the name of a Pokémon BUT in French.
Is there a way today to do this?
Otherwise could it happen?

Thank you in advance ! :)

**Comment by Naramsim** [comment]
Hi @MalronWall, currently search is not implemented at all. Not even in English. We offer an endpoint where you can get a Pokemon's name in different languages (https://pokeapi.co/api/v2/pokemon-species/34/ look at the `name` property) but that's it.

The best solution for your app would be to use directly the database and run an SQL query the filters out pokemons based on a given text. 

You can actually do this by following the docker-compose instructions present on the README. Be sure to check out one of the latest branch because the `master` is currently broken.

**Comment by MalronWall** [comment]
Hi @Naramsim and thank you for your answer ! :)
Too bad... I'm not using PHP or SQL for this project so I won't be able to use the db... :/
Thank you anyway!

**Comment by Naramsim** [comment]
Yeah, what I'm saying is that currently with only the API we offer you cannot achieve your goal. 

You could spin up a PokeAPI instance on a personal server, and with a custom script, you could extract the data you want and serve it.

**Comment by phalt** [comment]
I would either:

1) Keep a synced list of French -> English translations and use that as your "search", then convert to English, then call API.

2) As @Naramsim said - spin up your own instance of PokeAPI and add the stuff in point 1 to the API itself.

Won't happen on the core PokeAPI as it is feature-specific and not generic enough.

**Comment by MalronWall** [comment]
@Naramsim your solution can work indeed but I have the constraint to do everything in front (js, html, scss ...).
On the other hand, if I could find a translation list as @phalt suggests and convert it to a js table, it could work!
There is no such thing in this API by chance...? :/

**Comment by Naramsim** [comment]
Well, you can come up with a script that fetches each pokemon (~800 calls) and its translations. Then you can write a JSON file with all the English names and French ones:

```json
{
  "Bulbizarre": "Bulbasaur",
  ...
}
```

You have all the power in your hands :)

**Comment by Naramsim** [comment]
Consider also this link: https://bulbapedia.bulbagarden.net/wiki/List_of_French_Pok%C3%A9mon_names

**Comment by MalronWall** [comment]
Yes that's it ! ^^
I do not know if suddenly I will go as far in my functionality because it is rather long to do, but thank you in any case! :D
