### ISSUE TITLE
Implementing search

### ISSUE THREAD

**Issue by phalt** [PokeAPI/pokeapi#474]
Alrighty. What would it take to get search working? It's a popular request.

Let's go with this URI:

```
https://pokeapi.co/pokemon?search=bulb
```
Assume it returns results from the base resource page which have a name that includes the string. ([this one](https://pokeapi.co/api/v2/pokemon)).

Getting this working in the base project is easy as it is just a DRF view function.
But getting it working on the deployed firebase instance? I'm looking at you @Naramsim for some input. It's just JS code right? We can filter on the data I assume?

**Comment by Naramsim** [comment]
I see a potential _search feature_ having terrible cost-related problems. I know it's a cool feature but the problem is that the query string will be submitted/customized by the clients and all those different requests won't probably be cached by Cloudflare.

I foresee a search endpoint will be always hit with different input strings and clients won't rate limit themselves for sure, leading to a waterfall of requests towards PokeAPI such as:

```log
GET https://pokeapi.co/pokemon?search=b
GET https://pokeapi.co/pokemon?search=bu
GET https://pokeapi.co/pokemon?search=bul
GET https://pokeapi.co/pokemon?search=bulb
...
```

potentially on every pokemon/item/berry and so on. Any thoughts on this @phalt? It's something we cannot ignore.

You have to consider that right now we are surviving with 10 dollars a month because Cloudflare caches all our requests so that the cloud function we have on Firebase is only hit a few times. The more we hit it the more we pay.

**Comment by phalt** [comment]
Very good point @Naramsim - we can't rely on developers debouncing their requests. Given it is a teaching tool first and foremost - we will probably get people doing this a lot.

On a side note - are you able to grant me access to the firebase project just so we can reduce the risk of having few people with access?

**Comment by phalt** [comment]
Perhaps we can implement it on the core python project and allow people to download and run their own instance if they need search?

**Comment by Naramsim** [comment]
Yeah, maybe we could have a flag that enables the feature

**Comment by ShinteiMai** [comment]
@phalt I think that's the best way atleast for right now, If PokeAPI keeps growing in the future (and hopefully have more money), I think it's possible to just merge the branch that has the search feature into the production branch. Would love to contribute on the search feature if this discussion gets escalated.

**Comment by Naramsim** [comment]
If you have time and will you can start coding it and submit a PR 😄 

It would be much appreciated!

**Comment by PorterK** [comment]
@ShinteiMai Did you end up starting this? Would like this feature for an app I am working on (running pokeapi as a service within my ecosystem). Would hate to repeat any work that's already done.

**Comment by Naramsim** [comment]
No sorry, we didn't start any coding on this feature. 

Keep in mind that to speed things up you could get the list of all pokemon (https://pokeapi.co/api/v2/pokemon-species/), map it and search against it locally on the browser of the user. That way would be much more performant.

**Comment by Aaditya0086** [comment]
I was just exploring this API and came across this, Therefore I mapped all data and created just a search API with the static data. I am listing the API and endpoint, in-case someone wants to explore search with this API.

API URL with endpoint - https://pokemon-service-ucql.onrender.com/api/v1/pokemon/search?name=
Integrated Url(live-link) - https://pokemonmanagementsystem-aaditya0086s-projects.vercel.app/add

**Comment by Naramsim** [comment]
Search was implemented at some point. It's available if you host pokeapi locally. We don't provide this functionality at pokeapi.co due to costs
