### ISSUE TITLE
Writing about pokeapi-scrapper

### ISSUE THREAD

**Issue by adeelibr** [PokeAPI/pokeapi#478]
Hello,

First of all I would like to say 👌 awesome work on the pokeapi, I love it. This is not an issue something I just wanted to share here. I wrote a pokeapi scrapper https://github.com/adeelibr/pokeapi-scrapper

I was making a personal project of my own & i wanted mock data. I wanted to work with a data set without having to make network calls again & again. So I wrote a scrapper that get's a list of pokemon & stores it in a `.js` file.

Again thank you for this awesome work. :)

Please do let me know if it's okay to have this scrapper open sourced. If there is an issue I will delete the repo immediately.

**Comment by Naramsim** [comment]
Hello @adeelibr, thanks for the information. It seems a cool project and I guess you learned a lot while you were coding it, that's great.

Also consider that we publish our data offline here: https://github.com/PokeAPI/api-data

You should definitely leave the project open-source!

I'm going to close this issue now since this was just a piece of information and not a real problem. Also, consider subscribing to our Slack channel.
