### ISSUE TITLE
MissingNo. Pokemon 0

### ISSUE THREAD

**Issue by NathanBorchelt** [PokeAPI/pokeapi#566]
Pokemon #0: MissingNo.

I know it may not be the point, but an inclusion of MissingNo would be a nice little detail to include the glitched pokemon

**Comment by Kronopt** [comment]
That's actually an interesting idea.
But, as MissingNo. is not canon, I have my doubts about it being included in the API.

Discuss away, though

**Comment by Naramsim** [comment]
I also don't see it being added to the API. Besides, Bulbapedia lists several `0` pokemons.

https://bulbapedia.bulbagarden.net/wiki/000

**Comment by phalt** [comment]
I disagree purely because MissingNo is not a pokemon, it is the result of corrupted data producing "no values" - which fails gracefully to produce the "Missing Number" warning you see in the old games.

Criteria that would make me agree to add it:

- Present in later games
- Present pokedex entry
- Learnable move sets

**Comment by jannismain** [comment]
I was just in the process of adding this to my little game, when I saw that the sprite I get from `id=0` is a question mark instead of the Missingno sprite. If you have a `0.png` in your repository, why not make it the missingno sprite? :-)
