### ISSUE TITLE
Add nullable fields to the doc.

### ISSUE THREAD

**Issue by galatea21** [PokeAPI/pokeapi#683]
I haven't seen anything in the documentation that mark if a field is nullable or not. Is it possible to add this information to the doc?

**Comment by Naramsim** [comment]
Hi @galatea21, we have this info in the API but bringing it to the docs would be a bit tiresome and difficult. I don't expect someone will do it soon

**Comment by C-Garza** [comment]
You can look at the JSON schema for now to check what fields can be nullable: [JSON Schema](https://github.com/PokeAPI/api-data/tree/master/data/schema/v2)

@Naramsim, I could slowly start to add which fields could be null to the docs. I looked at the repo and I think it would only be a slight tweak to the React and then manually adjusting the docs response model field types to have an array of types where it could be nullable.

**Comment by Naramsim** [comment]
I'm not sure the schema is 100% correct since it's generated by scraping the API. Probably it's 99.9% correct but the best way to know if a field is nullable is to look at the Django fields in pokeapi: Berry example here https://github.com/PokeAPI/pokeapi/blob/master/pokemon_v2/models.py#L1017

Anyways, @C-Garza, up to you to decide whether implement it or not. I don't see this as a priority, but if you have fun doing it you are welcome :)

**Comment by mlemesle** [comment]
A little comment to show my interest in this discussion!
I'm currently improving my wrapping lib and knowing which fields are nullable and which aren't would be game changer for me!
