### ISSUE TITLE
Filter where id throws a syntax error in console 

### ISSUE THREAD

**Issue by martipello** [PokeAPI/pokeapi#774]
Steps to Reproduce:

1. Open console - https://beta.pokeapi.co/graphql/console/
2. Make a query where id equals a given id, moves, pokemon or pokedex are all examples 
example - query MyQuery {
                    pokemon_v2_pokedex(where: {id: {_eq: 1}}) {
                    name
                   }
                }  
3. expected result - results filtered by ID - actual result - invalid syntax error - SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by yannickcpnv** [comment]
I also get the same error with any request, except the one that is already present when you connect to the console for the first time.

I think this error happens in the console because we get a response in HTML format instead of JSON.
For me, when I check the network, the response is a 502 Bad gateway error :

![image](https://user-images.githubusercontent.com/78364651/203855435-f4e2f300-de16-4398-8694-61db3a38a40d.png)

I've been getting this error since this afternoon, and I've retried a lot of times 😄

**Comment by martipello** [comment]
Still an issue this morning

**Comment by Borrajo** [comment]
I found the same issue. I thought that I exceeded the query limit

**Comment by fabs88k** [comment]
Hello guys, same here.
Few requests seems to work, but most of them are returning 502.

**Comment by C-Garza** [comment]
@Naramsim it looks like the graphql service is down again.

**Comment by martipello** [comment]
Still not working 😭

**Comment by Naramsim** [comment]
closing, I restarted the server

**Comment by martipello** [comment]
I think i might be breaking it using the console, seems its not working again

**Comment by Borrajo** [comment]
it still doesn't working, but now with status code 504

**Comment by martipello** [comment]
yh shes dead jim
