### ISSUE TITLE
Missing move tables of 4th gen starter Pokémon

### ISSUE THREAD

**Issue by giginet** [PokeAPI/pokeapi#956]
New move tables of Pokémon since Teal Mask are introduced at https://github.com/PokeAPI/pokeapi/pull/920.

However, I found that the tables of some Pokémon seem to be wrong.

Strangely, as I found, the starter Pokémon of 4th gen have the wrong tables.
(Turtwig, Chimchar, Piplup, and their evolved Pokémon)

@penelopeysm Do you have time to fix the issue?

**Comment by penelopeysm** [comment]
Hi, @giginet, I think this is because when I added move data, I only accounted for the Pokemon that were in the Paldea / Kitakami Pokedex. The Gen 4 starters can be transferred in via Pokemon HOME but don't have dex entries.

My impression is that it isn't too much work for me to get these sorted, because I probably just need to rerun the same script on anything that wasn't caught last time. I'll try it and see.
